url: "https://rsegebre.github.io" # The base hostname & protocol for your site
baseurl: "" # The subpath of your site, e.g. /blog

title: "My Awesome Blog"
author: "rsegebre"
email: "your-email@example.com"
description: "A personal blog and portfolio."
lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

# Theme and Plugins
theme: minima

plugins: []